Vagrant.configure("2") do |config|
  # VM1: Загальнодоступний вебсервер
  config.vm.define "web_server" do |web|
    web.vm.box = "bento/ubuntu-24.04"
    web.vm.network "public_network", type: "dhcp"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.synced_folder "./web_shared", "/vagrant_web", create: 1
    web.vm.provision "shell", inline: <<-SHELL
      sudo apt update && sudo apt upgrade -y
      sudo apt install -y nginx
      sudo systemctl enable nginx
      sudo systemctl start nginx
    SHELL
  end

  # VM2: Приватний сервер
  config.vm.define "private_server" do |private_vm|
    private_vm.vm.box = "bento/ubuntu-24.04"
    private_vm.vm.network "private_network", ip: "192.168.50.10"
    private_vm.vm.synced_folder "./private_shared", "/vagrant_private", create: 1
    private_vm.vm.provision "shell", path: "./provision.sh"
  end

  # VM3: Загальнодоступний сервер зі статичним IP
  config.vm.define "public_static_server" do |public_static|
    public_static.vm.box = "bento/ubuntu-24.04"
    public_static.vm.network "public_network", ip: "192.168.1.100", bridge: "wlp3s0"
    public_static.vm.synced_folder "./public_shared", "/vagrant_public", create: 1
  end
end