Vagrant.configure("2") do |config|
    # Кількість машин
    num_machines = 3
    
    # Налаштування для кожної машини
    (1..num_machines).each do |i|
      config.vm.define "web_server#{i}" do |web|
        web.vm.box = "bento/ubuntu-24.04"
        web.vm.network "public_network", type: "dhcp"
        web.vm.network "forwarded_port", guest: 80, host: 8080+i
        web.vm.synced_folder "./web_shared#{i}", "/vagrant_web", create: 1
        web.vm.provision "shell", inline: <<-SHELL
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y nginx
          sudo systemctl enable nginx
          sudo systemctl start nginx
        SHELL
      end
    end
  end

  